- pacman_packages:
  - neovim
  - keynav
  - evtest
  - tmux
  - kitty

- name: Install packages with Pacman
  community.general.pacman:
    name: "{{ pacman_packages }}"
    state: present
      #with_items:
      #  - neovim
      #  - keynav
      #  - evtest
      #  - tmux
      #  - kitty

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: yes
  become_user: aur_builder
  with_items:
    - htop-vim
    - kmonad-bin
    - xfdashboard  # it doesn't show thumbnails + is scoped to one workspace
    # - rofi-blezz - the repo is dead, and it freezes ansible
    - neovide
