- name: copy unit files
  copy:
    src: "{{ item }}"
    dest: /usr/lib/systemd/system/
    owner: root
    #mode: 600
  with_fileglob:
    - ../systemd-unit-files/*

- name: enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - kmonad
    - keynav
