- name: Ensure we have autoload directory
  file:
    path: "/home/boris/.local/share/nvim/site/autoload"
    state: directory
  become: True
  become_user: boris

- name: Pull vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/boris/.local/share/nvim/site/autoload/plug.vim"
  become: True
  become_user: boris
